### ISSUE TITLE
Incompatible with WindowsAzure.Storage 7.2.1

### ISSUE THREAD

**Issue by PhilDye** [CrumpledDog/Umbraco-AzureLogger#10]
It looks like there was a breaking change in this dependency, which should therefore probably be constrained in the nuspec to 6.2.0.

Upgrading to WindowsAzure.Storage 7.2.1 causes an exception when opening a log detail entry in the backoffice;

```
    "ExceptionMessage": "Method not found: 'Microsoft.WindowsAzure.Storage.Table.TableOperation Microsoft.WindowsAzure.Storage.Table.TableOperation.Retrieve(System.String, System.String)'.",
    "ExceptionType": "System.MissingMethodException",
    "Message": "An error has occurred.",
    "StackTrace": "   at Our.Umbraco.AzureLogger.Core.TableService.ReadLogTableEntity(String appenderName, String partitionKey, String rowKey)
    at Our.Umbraco.AzureLogger.Core.Controllers.ApiController.ReadLogItemDetail(String appenderName, String partitionKey, String rowKey)
```

**Comment by Hendy** [comment]
Hi @PhilDye we've updated the WindowsAzure.Storage to 7.2.1, but have been unable to reproduce this issue (see latest develop branch)

**Comment by Jeavon** [comment]
@PhilDye were you using a UK region for your storage account?

**Comment by PhilDye** [comment]
@Jeavon No, North Europe

@Hendy I'm definitely able to reproduce, using Our.Umbraco.AzureLogger 0.2.0-beta (from nuget); with WindowsAzure.Storage 6.2.0 it's fine. However, doing an `update-package WindowsAzure.Storage` (to 7.2.1) causes the exception in the backoffice controller (/umbraco/BackOffice/AzureLogger/Api/ReadLogItemDetail).  Happy to Skype screenshare or something if it helps track it down?

**Comment by Jeavon** [comment]
@PhilDye could you try the latest alpha (v0.2.1-alpha-000163) from MyGet? https://www.myget.org/feed/umbraco-packages/package/nuget/Our.Umbraco.AzureLogger

**Comment by PhilDye** [comment]
I confirm that's working

**Comment by slothario** [comment]
By the way, for others out there who need a workaround for the TableOperation.Retrieve operation, here's a workaround:

`            string queryString =
                TableQuery.GenerateFilterCondition("PartitionKey", QueryComparisons.Equal, partitionKey);
            string queryString2 =
                TableQuery.GenerateFilterCondition("RowKey", QueryComparisons.Equal, rowKey);
            string finalQuery = TableQuery.CombineFilters(queryString, TableOperators.And, queryString2);

            var query = new TableQuery<GenericTableEntity>().Where(finalQuery);

            TableQuerySegment<GenericTableEntity> segment = Task.Factory
                .FromAsync<TableQuery<GenericTableEntity>, TableContinuationToken, TableQuerySegment<GenericTableEntity>>(
                    _table.BeginExecuteQuerySegmented,
                    _table.EndExecuteQuerySegmented<GenericTableEntity>, query, null, null).Result;
            var res = segment.Results.SingleOrDefault();`
